"""add tariffs to parcel_types

Revision ID: 682e019805ed
Revises: cacdd4edef83
Create Date: 2025-12-22 20:46:49.657332

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "682e019805ed"
down_revision: str | Sequence[str] | None = "cacdd4edef83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parcel_types",
        sa.Column("base_price_usd", sa.Numeric(precision=12, scale=2), nullable=False),
    )
    op.add_column(
        "parcel_types",
        sa.Column("price_per_kg_usd", sa.Numeric(precision=12, scale=2), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parcel_types", "price_per_kg_usd")
    op.drop_column("parcel_types", "base_price_usd")
    # ### end Alembic commands ###
