"""add session_id and content fields to parcels

Revision ID: 855ffc702f88
Revises: 682e019805ed
Create Date: 2025-12-24 18:03:29.375128

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "855ffc702f88"
down_revision: str | Sequence[str] | None = "682e019805ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parcels", sa.Column("session_id", sa.String(length=128), nullable=False))
    op.add_column("parcels", sa.Column("title", sa.String(length=128), nullable=False))
    op.add_column(
        "parcels", sa.Column("content_usd", sa.Numeric(precision=12, scale=2), nullable=False)
    )
    op.add_column(
        "parcels", sa.Column("delivery_cost_rub", sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.create_index(op.f("ix_parcels_session_id"), "parcels", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parcels_session_id"), table_name="parcels")
    op.drop_column("parcels", "delivery_cost_rub")
    op.drop_column("parcels", "content_usd")
    op.drop_column("parcels", "title")
    op.drop_column("parcels", "session_id")
    # ### end Alembic commands ###
