"""add session_id to parcels

Revision ID: aa5125124665
Revises: 855ffc702f88
Create Date: 2025-12-25 09:28:35.887614

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa5125124665"
down_revision: str | Sequence[str] | None = "855ffc702f88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parcels",
        "session_id",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parcels",
        "session_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
