"""create parcels and parcel_types

Revision ID: cacdd4edef83
Revises:
Create Date: 2025-12-22 13:47:29.775616

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cacdd4edef83"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parcel_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parcel_types_code"), "parcel_types", ["code"], unique=True)
    op.create_table(
        "parcels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parcel_type_id", sa.UUID(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parcel_type_id"], ["parcel_types.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parcels_parcel_type_id"), "parcels", ["parcel_type_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parcels_parcel_type_id"), table_name="parcels")
    op.drop_table("parcels")
    op.drop_index(op.f("ix_parcel_types_code"), table_name="parcel_types")
    op.drop_table("parcel_types")
    # ### end Alembic commands ###
